spring:
  application:
    name: FoodSafe
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:food.db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        format_sql: true
    database-platform: com.my.foodsafe.dialect.SQLiteDialect
google:
  vision:
    api:
      key: AIzaSyBa08m_sX3yB1VgfeEh9ue_mSO6QgVkdTI

